--- 
- 
  gather_fact: false
  hosts: bigip
  name: "Create a VIP, pool, pool members, and nodes"
  tasks: 
    - 
      bigip_pool: 
        lb_method: "{{ item.lb-method }}"
        name: "{{ item.name }}"
        password: "{{ password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        validate_certs: false
      delegate_to: localhost
      name: "Create a pool"
      with_items: "{{ pool_information }}"
    - 
      bigip_node: 
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        password: "{{ password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        validate_certs: false
      delegate_to: localhost
      name: "Create node"
      with_items: "{{ node_information }}"
    - 
      bigip_pool_member: 
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        password: "{{ password }}"
        pool: web
        port: 80
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        validate_certs: false
      delegate_to: localhost
      name: "Add nodes to pool"
      with_items: 
        - 
          host: "172.16.20.1"
          name: node-1
        - 
          host: "172.16.20.2"
          name: node-2
        - 
          host: "172.16.20.3"
          name: node-3
  vars_files: 
    - var_config-file.yml
